### ISSUE TITLE
Affectiva SDK crashing when compiled with aws sdk

### ISSUE THREAD

**Issue by nikhilvs** [Affectiva/cpp-sdk-samples#28]
Hi,

When affectiva library is integrated into my application, which has dependency on aws sdk. Application crashes , once i removes aws sdk dependency module it works fine. From application dump, i can understand that libaffdex-native.so is using aws sdk, which is clashing with my aws sdk module.

aws-sdk version : Latest codebase from github
gcc,g++ version : 4.9

- How can aws sdk of my app and affectiva sdk run together or co exist ?
- I also noticed some exception been thrown from your sdk, even when it is running normal.

I would like to know if am doing something wrong or some configuration is wrong.

Please find attachments below for the core dump's of above 2 scenarios.

[cmake-output.txt](https://github.com/Affectiva/cpp-sdk-samples/files/1119614/cmake-output.txt)
[dump-integrated-into-app.txt](https://github.com/Affectiva/cpp-sdk-samples/files/1119615/dump-integrated-into-app.txt)
[run-normal-with-valgrind.txt](https://github.com/Affectiva/cpp-sdk-samples/files/1119616/run-normal-with-valgrind.txt)

**Comment by adennie** [comment]
Hi @nikhilvs, we recently got our SDK support forum up and running at http://discuss.affectiva.com/c/emotion-sdk.  If this issue is not related to the samples in this repo, we ask that you please raise it in the forum instead.  We're trying to keep things organized by handling SDK issues in the forum (or StackOverflow, for more general questions), and keeping Github issues focused on the repo they're raised in.  Thanks very much.

**Comment by nikhilvs** [comment]
Sure

**Comment by adennie** [comment]
Issue moved to discussion forum, closing here.
